### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by fnielsen** [eea/sparql-client#11]
Python 3 is not supported. I would be nice if there was a support for these versions.

The exception line generates an SyntaxError Exception.

      File "/usr/local/lib/python3.5/dist-packages/sparql.py", line 477
        except Exception, error:
                        ^
    SyntaxError: invalid syntax
    >>> 

The comma should be changed to ' as'. Or do you still want to support 2.5? 

Whether the 'as' will clear all problems for python3 I do not know.

**Comment by AtomsForPeace** [comment]
Trying to work on a version here if anyone wants to help: https://github.com/AtomsForPeace/sparql-client/tree/python3

Would have to drop support for earlier 2 versions though of course.

**Comment by danmichaelo** [comment]
@avoinea, are you ok with dropping support for Python < 2.7? The effort by @AtomsForPeace might need a little tweaking, but looks very promising!

**Comment by avoinea** [comment]
@danmichaelo Yes. We need it on Python 2.7+

**Comment by vnktsh** [comment]
@avoinea Can you add this to README file that it doesn't support Python 3 yet?

**Comment by dbrnz** [comment]
Given that Python 2.7 will be end-of-life in less than 6 months, when will an official Python 3 version be released??

**Comment by alecghica** [comment]
Python 3 is supported for some time now.
