### ISSUE TITLE
Parameterized query

### ISSUE THREAD

**Issue by wonkydonky** [eea/sparql-client#15]
Is it possible to use this library to create a SPARQL query using parameters? I'm trying to avoid string concatenation for building my queries, but I can't find any library that does this.

**Comment by vikash18086** [comment]
[https://github.com/eea/sparql-client/pull/25](url)
You can now make a prepare_query object as 'ps' in which you can send the query as a string with values you want to set as in format '@_name' and then use .set function to set that variable name. Then you can pass 'ps' object through my_own() function to get the result using the parameterized query.

**Comment by sorinstelian** [comment]
This looks like a request for an utility function for query string formatting. Such a feature would be best implemented in an external package, as it is outside the scope of this package.
