### ISSUE TITLE
Comment in the SPARQL query errs

### ISSUE THREAD

**Issue by fnielsen** [eea/sparql-client#4]
A comment in the query with the '#' character makes my version of sparql errs. I am on 0.17-dev installed from the Cheeseshop.

For example, "# Q35 is Denmark" in the below query throws a sparql.SparqlException:

    import sparql
    service = sparql.Service("https://query.wikidata.org/bigdata/namespace/wdq/sparql")
    statement = """
    PREFIX wd: <http://www.wikidata.org/entity/> 
    PREFIX wdt: <http://www.wikidata.org/prop/direct/>
    SELECT ?location WHERE {
       ?location wdt:P17 wd:Q35 .        # Q35 is Denmark
    } LIMIT 2
    """
    result = service.query(statement)

**Comment by fnielsen** [comment]
The perpetrator may be line 523 with statement.replace("\n", " ")

**Comment by zotya** [comment]
Thanks for reporting this issue, we added it to our queue: https://taskman.eionet.europa.eu/issues/72876
Until it's fixed you could try to avoid the comments inside the query, or to simply comment the statement.replace line.

**Comment by zotya** [comment]
The fix was applied in
https://github.com/eea/sparql-client/commit/8b2c7af634bca0898fa37579b6869e1f5de56d7c
It will be available also in the egg version 2.2

**Comment by alecghica** [comment]
the new egg will be released on PyPi in the following days.
