### ISSUE TITLE
Why are there no releases on pypi after 1.3?

### ISSUE THREAD

**Issue by djowett** [eea/sparql-client#5]

**Comment by djowett** [comment]
This is causing me trouble when trying to build eea.dataviz on Ubuntu - because versions of this product before 1.7 pull in pycurl2, I've got requirements on libraries on Ubuntu that I can't (yet) find.  I'm hoping that the switch to eventlet might require less obscure platform dependencies.  Hence my need to get at releases of 1.7 / 1.8 of this product

**Comment by alecghica** [comment]
The egg release series is fine now, see https://pypi.python.org/simple/sparql-client
