### ISSUE TITLE
__version__ does not correspond to package version

### ISSUE THREAD

**Issue by fnielsen** [eea/sparql-client#8]
The `__version__` variable does not correspond to the package version. 

[Line 65](https://github.com/eea/sparql-client/blob/master/sparql.py#L65) sets it to 0.17-dev while both present PYPI and Github versions are newer.

See also issue #7.

**Comment by alecghica** [comment]
@fnielsen thank you for reporting this issue. We track it under our internal ticketing system and you can see status at https://taskman.eionet.europa.eu/issues/74283

The ticket need to be approved first by the product owner in order to be solved.

**Comment by avoinea** [comment]
Fixed.
